#pragma once

#define MAIN_Version "4b28b19"
#define KNX_Version "2.1.2+8257add"
#define MODULE_Common_Version "1.3.0+122cd50"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 3
#define MODULE_Common_Version_Revision 0
#define MODULE_Common_ETS 19
#define MODULE_LogicModule_Version "3.5.2+2dbceb4"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 5
#define MODULE_LogicModule_Version_Revision 2
#define MODULE_LogicModule_ETS 53
#define MODULE_ShutterControllerModule_Version "0.3.1+54e84af"
#define MODULE_ShutterControllerModule_Version_Major 0
#define MODULE_ShutterControllerModule_Version_Minor 3
#define MODULE_ShutterControllerModule_Version_Revision 1
#define MODULE_ShutterControllerModule_ETS 3
#define MODULE_FileTransferModule_Version "0.0.5+e39c804"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 0
#define MODULE_FileTransferModule_Version_Revision 5
#define MODULE_FileTransferModule_ETS 0
#define MODULE_UsbExchange_Version "0.0.1+1ce7a13"
#define MODULE_UsbExchange_Version_Major 0
#define MODULE_UsbExchange_Version_Minor 0
#define MODULE_UsbExchange_Version_Revision 1
#define MODULE_UsbExchange_ETS 0
#define MODULE_FunctionBlocks_Version "0.4.0-DEV+1d1a22c"
#define MODULE_FunctionBlocks_Version_Major 0
#define MODULE_FunctionBlocks_Version_Minor 4
#define MODULE_FunctionBlocks_Version_Revision 0
